"""empty message

Revision ID: 2699a9e16350
Revises: 
Create Date: 2022-05-29 14:15:08.987073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2699a9e16350'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('home_country', sa.Text(), nullable=False),
    sa.Column('destination_city', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mission')
    # ### end Alembic commands ###
